version: '3.4'

services:
  api:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env/.dev
    volumes:
      - ./web/static/:/app/web/static/
    depends_on:
      - broker
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env/.dev
  broker:
    image: redis:7-alpine
  worker:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "api", "worker", "--loglevel=info"]
    env_file:
      - ./.env/.dev
    depends_on:
      - broker
  scheduler:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "api", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file:
      - ./.env/.dev
    depends_on:
      - broker
  monitor:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5555:5555
    command: ["celery", "-A", "api", "flower", "--port=5555"]
    env_file:
      - ./.env/.dev
    depends_on:
      - broker

volumes:
  db_data:
