version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env/.dev
    depends_on:
      - redis
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env/.dev
  redis:
    image: redis:7-alpine
  celery:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "api", "worker", "--loglevel=info"]
    env_file:
      - ./.env/.dev
    depends_on:
      - redis
  flower:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5555:5555
    command: ["celery", "-A", "api", "flower", "--port=5555"]
    env_file:
      - ./.env/.dev
    depends_on:
      - redis

volumes:
  pg_data:
