version: '3.4'

services:
  api:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env/.prod
    depends_on:
      - broker
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/.prod
  broker:
    image: redis:7-alpine
  worker:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "api", "worker", "--loglevel=info"]
    env_file:
      - ./.env/.prod
    depends_on:
      - broker
  beat:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["celery", "-A", "api", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file:
      - ./.env/.prod
    depends_on:
      - broker
  monitor:
    image: aaos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5555:5555
    command: ["celery", "-A", "api", "flower", "--port=5555"]
    env_file:
      - ./.env/.prod
    depends_on:
      - broker

volumes:
  pg_data:
