apiVersion: v1
data:
  CELERY_BACKEND: redis://broker:6379/0
  CELERY_BROKER: redis://broker:6379/0
  DJANGO_ALLOWED_HOSTS: '*'
  DEBUG: "True"
  ELASTIC_APM_DEBUG: "True"
  ELASTIC_APM_LOG_LEVEL: debug
  ELASTIC_APM_SERVICE_NAME: aaos
  ELASTIC_APM_VERIFY_SERVER_CERT: "True"
  POSTGRES_DB: aaos
  POSTGRES_USER: aaos
  SQL_DATABASE: aaos
  SQL_ENGINE: django.db.backends.postgresql
  SQL_HOST: cer1-pgdev.postgres.database.azure.com
  SQL_PORT: "5432"
  SQL_USER: aaos
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-aaos
  name: aaos-dev
