apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: pv-db-data
  resources:
    requests:
      storage: 5Gi