name: docker
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push aaos
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/aaos:dev
      -
        name: Build and push aaos-dev
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/aaos-web:dev